// Code generated for olezhek28 service
// © Olezhek28 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "golearning/inventory/internal/repository/model"

	mock "github.com/stretchr/testify/mock"
)

// PartRepository is an autogenerated mock type for the PartRepository type
type PartRepository struct {
	mock.Mock
}

type PartRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PartRepository) EXPECT() *PartRepository_Expecter {
	return &PartRepository_Expecter{mock: &_m.Mock}
}

// GetPart provides a mock function with given fields: ctx, filter
func (_m *PartRepository) GetPart(ctx context.Context, filter model.GetPartFilter) (*model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetPartFilter) (*model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetPartFilter) *model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetPartFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartRepository_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type PartRepository_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.GetPartFilter
func (_e *PartRepository_Expecter) GetPart(ctx interface{}, filter interface{}) *PartRepository_GetPart_Call {
	return &PartRepository_GetPart_Call{Call: _e.mock.On("GetPart", ctx, filter)}
}

func (_c *PartRepository_GetPart_Call) Run(run func(ctx context.Context, filter model.GetPartFilter)) *PartRepository_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GetPartFilter))
	})
	return _c
}

func (_c *PartRepository_GetPart_Call) Return(_a0 *model.Part, _a1 error) *PartRepository_GetPart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartRepository_GetPart_Call) RunAndReturn(run func(context.Context, model.GetPartFilter) (*model.Part, error)) *PartRepository_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function with given fields: ctx, filter
func (_m *PartRepository) ListParts(ctx context.Context, filter model.ListPartsFilter) ([]*model.Part, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*model.Part
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ListPartsFilter) ([]*model.Part, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ListPartsFilter) []*model.Part); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Part)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ListPartsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PartRepository_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type PartRepository_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.ListPartsFilter
func (_e *PartRepository_Expecter) ListParts(ctx interface{}, filter interface{}) *PartRepository_ListParts_Call {
	return &PartRepository_ListParts_Call{Call: _e.mock.On("ListParts", ctx, filter)}
}

func (_c *PartRepository_ListParts_Call) Run(run func(ctx context.Context, filter model.ListPartsFilter)) *PartRepository_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ListPartsFilter))
	})
	return _c
}

func (_c *PartRepository_ListParts_Call) Return(_a0 []*model.Part, _a1 error) *PartRepository_ListParts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PartRepository_ListParts_Call) RunAndReturn(run func(context.Context, model.ListPartsFilter) ([]*model.Part, error)) *PartRepository_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// NewPartRepository creates a new instance of PartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PartRepository {
	mock := &PartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
