// Code generated for olezhek28 service
// © Olezhek28 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	model "golearning/payment/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

type PaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentRepository) EXPECT() *PaymentRepository_Expecter {
	return &PaymentRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, payment
func (_m *PaymentRepository) Save(ctx context.Context, payment model.Payment) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Payment) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type PaymentRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - payment model.Payment
func (_e *PaymentRepository_Expecter) Save(ctx interface{}, payment interface{}) *PaymentRepository_Save_Call {
	return &PaymentRepository_Save_Call{Call: _e.mock.On("Save", ctx, payment)}
}

func (_c *PaymentRepository_Save_Call) Run(run func(ctx context.Context, payment model.Payment)) *PaymentRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Payment))
	})
	return _c
}

func (_c *PaymentRepository_Save_Call) Return(_a0 error) *PaymentRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentRepository_Save_Call) RunAndReturn(run func(context.Context, model.Payment) error) *PaymentRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentRepository creates a new instance of PaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepository {
	mock := &PaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
